version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: next-shop-postgres
    environment:
      POSTGRES_USER: nextshop_user
      POSTGRES_PASSWORD: nextshop_password
      POSTGRES_DB: nextshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
